spring:
  datasource:
    url: jdbc:h2:mem:products
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update      
    
server:
  port: 8090
  
#logging:
  #config: classpath:logback-spring.xml
 # file:
  #  name: /Users/pradeep/Documents/softwares/apache-tomcat-9.0.65-prod/logs/devops.log
 # level:
   # root: INFO
    
   # '[org.springframework.web]': INFO
